Add discord bot example
modal-labs/modal-examples pull request #1027
Opened 2024-12-29 22:49 UTC by advay-modal

Part of initiative to split out boombot into 2 separate examples, one for discord and one for musicgen.

In this example I make a discord bot that just takes a city and returns the weather. 

### Type of Change

- New example

## Checklist

- Example is testable in synthetic monitoring system, or `lambda-test: false` is added to example frontmatter (`---`)
- Example is documented with comments throughout, in a [_Literate Programming_](https://en.wikipedia.org/wiki/Literate_programming) style.
- Example does _not_ require third-party dependencies to be installed locally
- Example pins its dependencies
- Example pins container images to a stable tag, not a dynamic tag like `latest`
- Example specifies a `python_version` for the base image, if it is used
- Example pins all dependencies to at least minor version, `~=x.y.z` or `==x.y`
- Example dependencies with `version < 1` are pinned to patch version, `==0.y.z`

## Outside contributors

You're great! Thanks for your contribution.

2024-12-29 22:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-876e0ff.modal.run

2024-12-29 22:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-f678863.modal.run

2024-12-29 22:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-df4c7a6.modal.run

2024-12-29 22:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-5fbf2b4.modal.run

2024-12-29 22:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-2a88f11.modal.run

2024-12-29 22:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-f4dc284.modal.run

2024-12-29 23:02 UTC, advay-modal commented
<img width="1436" alt="Screenshot 2024-12-29 at 5 44 18 PM" src="https://github.com/user-attachments/assets/e041437a-76a3-4b0e-bb0b-dbab995f79d9" />

2024-12-29 23:02 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-c594693.modal.run

2024-12-29 23:04 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-65995a4.modal.run

2024-12-29 23:19 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-d021a61.modal.run

2024-12-30 04:00 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-51ed462.modal.run

2024-12-30 11:04 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-ea5459b.modal.run

2025-01-02 15:13 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-db54a17.modal.run

2025-01-02 15:27 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-3654188.modal.run

2025-01-03 03:09 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-d8a4903.modal.run

2025-01-03 03:39 UTC, charlesfrye requested changes

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# (quick links: [try it out on Discord](https://discord.gg/nR96BxPu))
I think it's a good idea to host an example, but we should take care to:
1. Make it a Modal-branded Discord server.
2. Restrict all permissions for members except running slash commands.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# lambda-test: false
Why not test this?

Ideally, we QA this two ways:
1. Set `deploy: true` so that the example is deployed continuously and include a link to the hosted version so that users can try it and complain to us when it's broken
1. Use `modal run` in Lambda testing to check that the example is working (either the full deployed version or some subset of the logic).

It's a bit tough to check that the whole example application is working because we are not Discord (the requests have to be signed using Discord's private key and the responses are sent to a URL defined by an interaction token from Discord).

So I would maybe advocate for splitting up the logic here -- the `get_weather_forecast_for_city` function handles talking to the external API AND sending back to Discord. If it just talked to the external API, we could wrap it in another function that handles Discord integration.

Decomposing it also provides an opportunity to explain what's going on in the logic -- why do we have these interaction tokens and application IDs? What's with `session.patch` (that's a rare HTTP verb)? This all comes from the Discord docs, to which we should link.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +#    as the value of the `DISCORD_PUBLIC_KEY` environment variable.
This is actually pretty weird -- the public key is not secret nor is it really ours. It's owned by Discord and they use it to authenticate with _us_. It is specific to our app, but it's actually public information.

Leaking it is harmless on its own, because Discord is the entity that takes actions using it. An adversary would need to compromise our secrets or Discord's in order to trigger Discord to use the key.

Really, we should put the Secrets used to _register_ the slash command into Modal, along with the logic, and then this public key can come along for the ride.

See [this code](https://github.com/the-full-stack/ask-fsdl/blob/b725c0ecdf0d484b48b79e32c37905614522ba4d/bot.py#L207) I wrote for Full Stack Deep Learning. The whole thing is a lot cleaner than the code in Boombot.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# 3. [Create a custom Modal secret](https://modal.com/docs/guide/secrets) for your Discord bot.
```suggestion
# 3. [Create a custom Modal Secret](https://modal.com/docs/guide/secrets) for your Discord bot.
```

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +#    On Modal's secret creation page, select 'Discord'. Copy your Discord application’s
```suggestion
#    On Modal's Secret creation page, select 'Discord'. Copy your Discord application’s
```

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +#    Name this secret `weather-discord-secret`.
```suggestion
#    Name this Secret `weather-discord-secret`.
```

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# ## Defining the asgi app with modal
There's a lot of code in between this title/description and the actual ASGI app creation.

Even apart from splitting up the logic further, the prose and code organization also needs to be split up further. The logic for what our service does is separate from how we serve it -- even though our service here is pretty simple.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# We define an [Image](https://modal.com/docs/guide/images) that has the [`python-weather`](https://github.com/null8626/python-weather) package and
This doesn't add much beyond what's in the code.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# Note that since Discord requires an interaction response within 3 seconds, we
This prose is in the wrong place -- the function below doesn't have any of this logic.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# We now define an asgi app using the Modal ASGI syntax [@asgi_app](https://modal.com/docs/guide/webhooks#serving-asgi-and-wsgi-apps).
This comment doesn't add much.

This is where I would put the information that is beneath the "Defining the asgi app" header above.

I would also comment on the `keep_warm` choice -- the cost and why we're doing it.

Note that the need to keep a container warm to hit Discord's time limits pulls us away from a "true serverless" model. It's also pretty unlikely that someone would need to scale up a Discord bot beyond what a single FastAPI replica can handle, so we should focus on the idea of scaling up the _backend_ and on separation of concerns between the backend service and the API in front of it.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +    keep_warm=1,  # eliminates risk of container startup making discord ack time too long
We should also `allow_concurrent_inputs` here -- no need to spin up a replica for every call from Discord.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +@app.function(image=image)
Any part that uses `async` should have `allow_concurrent_inputs` set.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +    # allow CORS
A comment or at least a link here would be good.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +    async def get_weather_forecast_api(request: Request):
The names on the functions in this are a bit messy. Could we clean them up? Like this could just be `get_weather_forecast` or just `get_weather`, as could the function above.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +        # Verify the request using the Discord public key
Verify the request _is from Discord_

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +        if data.get("type") == 1:  # ack ping from Discord
An enum would be good here, see [this code](https://github.com/the-full-stack/ask-fsdl/blob/b725c0ecdf0d484b48b79e32c37905614522ba4d/bot.py#L23-L34).

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +    async def get_weather_forecast_api(request: Request):
Ah, we can't shadow it as-is because we later need a handle to call `.spawn` on within this scope.

I think we might be able to remove that constraint if we change the composition here -- but it might just end up uglier. In that case, can only get slightly cleaner names.

2025-01-03 03:39 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +def web_app():
I've started to dislike `web_app` as a name. Really, it's an API! So we should call these functions `api` or `web_api` in our examples. That also makes the final URL shorter.

2025-01-03 03:43 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +    city: str, interaction_token, application_id
This function is doing a bit too much -- figuring out the Discord URL to talk to, hitting a different external API, and then submitting the request. That makes it harder to write about and harder to effectively name.

2025-01-03 17:31 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-fcf035c.modal.run

2025-01-03 17:31 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-1834262.modal.run

2025-01-03 17:31 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-a90ca64.modal.run

2025-01-03 19:22 UTC, advay-modal commented on 07_web_endpoints/discord_bot.py
> +#    as the value of the `DISCORD_PUBLIC_KEY` environment variable.
What's the advantage of having the ability to register a slash command as a modal function? Imo if we do that we'd have to get the user to run this separate function before they run anything else on the app

2025-01-03 19:28 UTC, advay-modal commented on 07_web_endpoints/discord_bot.py
> +# We now define an asgi app using the Modal ASGI syntax [@asgi_app](https://modal.com/docs/guide/webhooks#serving-asgi-and-wsgi-apps).
"so we should focus on the idea of scaling up the backend and on separation of concerns between the backend service and the API in front of it." -> wdym by focus?

2025-01-03 19:32 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +#    as the value of the `DISCORD_PUBLIC_KEY` environment variable.
1. Creating a slash command in Modal requires secret information, which you can put in the Secret. It's a better demonstration of what Secrets are for. It's a bit weird that we're using it for configuration alone.
2. Including the setup in the code itself makes the example more self-contained and less error-prone (are you confident that snippet runs in _all_ shells?). You can add a call to that Function in the local entrypoint, you just need to make it idempotent (e.g. with a `force` or `overwrite` flag, as in the linked code [here](https://github.com/the-full-stack/ask-fsdl/blob/b725c0ecdf0d484b48b79e32c37905614522ba4d/bot.py#L235-L253)).

2025-01-03 19:40 UTC, charlesfrye commented on 07_web_endpoints/discord_bot.py
> +# We now define an asgi app using the Modal ASGI syntax [@asgi_app](https://modal.com/docs/guide/webhooks#serving-asgi-and-wsgi-apps).
Yeah, "focus on" as in "focus the prose in the example on".

My point is that the Discord bot hosting itself is not super compelling, especially now that we have a floor for CPU usage.

2025-01-18 04:40 UTC, charlesfrye approved these changes

2025-01-18 04:44 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-997f8ca.modal.run

2025-01-18 04:45 UTC, merged