Add music gen example
modal-labs/modal-examples pull request #1028
Opened 2024-12-30 12:01 UTC by advay-modal

2nd PR to split out boombot into 2 diff examples

### Type of Change

- [ ] New example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

## Checklist

- [ ] Example is testable in synthetic monitoring system, or `lambda-test: false` is added to example frontmatter (`---`)
  - [ ] Example is tested by executing with `modal run` or an alternative `cmd` is provided in the example frontmatter (e.g. `cmd: ["modal", "deploy"]`)
  - [ ] Example is tested by running with no arguments or the `args` are provided in the example frontmatter (e.g. `args: ["--prompt", "Formula for room temperature superconductor:"]`
- [ ] Example is documented with comments throughout, in a [_Literate Programming_](https://en.wikipedia.org/wiki/Literate_programming) style.
- [ ] Example does _not_ require third-party dependencies to be installed locally
- [ ] Example pins its dependencies
  - [ ] Example pins container images to a stable tag, not a dynamic tag like `latest`
  - [ ] Example specifies a `python_version` for the base image, if it is used
  - [ ] Example pins all dependencies to at least minor version, `~=x.y.z` or `==x.y`
  - [ ] Example dependencies with `version < 1` are pinned to patch version, `==0.y.z`

## Outside contributors

You're great! Thanks for your contribution.

2024-12-30 12:07 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-2cda415.modal.run

2024-12-31 13:31 UTC, kristiankauffeld commented
how would you expose this functionality through a web-API endpoint with a custom route like "/predict"?

2025-01-02 16:28 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-64c8dc7.modal.run

2025-01-02 16:33 UTC, advay-modal commented
you could do something like this:

`@app.function(
    image=web_image,
)
@asgi_app()
def ui():
    from fastapi import FastAPI

    web_app = FastAPI()
    model = Audiocraft()

    # Create a temporary directory for audio files
    temp_dir = Path("/tmp/audiocraft")
    temp_dir.mkdir(exist_ok=True, parents=True)

    @web_app.post("/predict")
    def generate_music(
        prompt: str,
        duration: int = 10,
        format: str = "wav",
        melody_url: str = "",
    ):
        clip_audio_bytes, melody_clip_audio_bytes = model.generate.remote(
            prompt, duration, format, melody_url
        )

        # Create a unique filename for this generation
        clip_file = f"{temp_dir}/generated_music_{uuid.uuid4()}.{format}"
        # Save bytes to temporary file that Gradio can serve
        with open(clip_file, "wb") as f:
            f.write(clip_audio_bytes.read())

        melody_clip_file = None
        if melody_clip_audio_bytes is not None:
            melody_clip_file = f"{temp_dir}/melody_clip{uuid.uuid4()}.{format}"
            with open(melody_clip_file, "wb") as f:
                f.write(melody_clip_audio_bytes.read())

        return clip_file, melody_clip_file

    return web_app

2025-01-02 16:54 UTC, kristiankauffeld commented
is it ok if I push a commit to this branch?

2025-01-02 18:13 UTC, kristiankauffeld commented
made a PR towards this branch

2025-01-02 20:31 UTC, charlesfrye requested changes
Mostly minor nits and comments.

I do think we want to avoid replicating the wav-handling code here, cf the comment on L70.

2025-01-02 20:31 UTC, charlesfrye commented on 06_gpu_and_ml/music_gen.py
> +@app.cls(gpu=gpu.A10G(), image=image)
```suggestion
@app.cls(gpu=gpu.L40S(), image=image)
```

2025-01-16 23:21 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-aebb4a6.modal.run

2025-01-17 01:36 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-6f563f8.modal.run

2025-01-17 06:05 UTC, charlesfrye approved these changes

2025-01-17 06:07 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-b5a546f.modal.run

2025-01-17 06:11 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-8874c05.modal.run

2025-01-17 06:13 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-a44f069.modal.run

2025-01-17 06:14 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-eb883b3.modal.run

2025-01-17 06:14 UTC, merged