Create multion_news_agent.py
modal-labs/modal-examples pull request #549
Opened 2024-01-16 03:47 UTC by Div99

### Type of Change

- [X ] New Example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

## Checklist

- [X ] Example is testable in synthetic monitoring system, or `lambda-test: false` is added to example frontmatter
- [ ] Example does _not_ require third-party dependencies to be installed locally
- [ ] Example is documented with comments throughout, in a [_Literate Programming_](https://en.wikipedia.org/wiki/Literate_programming) style.

## Outside contributors

You're great! Thanks for your contribution.

2024-01-16 03:47 UTC, Div99 commented
@aksh-at

2024-01-17 23:08 UTC, aksh-at requested changes
great, thanks for adding this! Couple comments but main one is that it would be great to explain to users what MultiOn is and how to set it up :)

2024-01-17 23:08 UTC, aksh-at commented on 10_integrations/multion_news_agent.py
> +QUERY = "serverless"
I don't think these constants are used anywhere

2024-01-17 23:08 UTC, aksh-at commented on 10_integrations/multion_news_agent.py
> +# Let's also define an image that has the `requests` package installed, so we can query the API.
```suggestion
# Let's also define an image that has the `muliton` package installed, so we can query the API.
```

2024-01-17 23:08 UTC, aksh-at commented on 10_integrations/multion_news_agent.py
> +# We can now define our main entrypoint, that use MultiOn to scrape AI news everyday and post it on my twitter account. We specify a [schedule](/docs/guide/cron) in the function decorator, which
```suggestion
# We can now define our main entrypoint, that uses [MultiOn](https://www.multion.ai/) to scrape AI news everyday and post it on our twitter account. We specify a [schedule](/docs/guide/cron) in the function decorator, which
```

2024-01-17 23:08 UTC, aksh-at commented on 10_integrations/multion_news_agent.py
> +# We can now define our main entrypoint, that use MultiOn to scrape AI news everyday and post it on my twitter account. We specify a [schedule](/docs/guide/cron) in the function decorator, which
Can we add a section that explains what MultiOn is, and how to set it up for this example? I.e. I have to make an account, install a chrome extension, log in to my Twitter (?)

2024-01-18 16:34 UTC, aksh-at approved these changes
Looks like there's a couple typos, but good to go otherwise!

2024-01-18 19:42 UTC, merged