add headings to some ml examples
modal-labs/modal-examples pull request #885
Opened 2024-09-20 21:38 UTC by kning

Starting with the `06_gpu_and_ml` folder. The `spam_detect` and `text-to-pokemon` apps I'm not entirely sure what to do with

2024-09-20 23:16 UTC, charlesfrye requested changes

2024-09-20 23:16 UTC, charlesfrye commented on 06_gpu_and_ml/stable_diffusion/flux.py
> +# This example runs the popular [Flux.1-schnell](https://www.google.com/search?client=firefox-b-1-d&q=flux+schnell+) text-to-image model on Modal.
This link looks wrong

2024-09-20 23:16 UTC, charlesfrye commented
You can ignore those two examples.

2024-09-23 14:47 UTC, kning commented on 06_gpu_and_ml/stable_diffusion/flux.py
> +# This example runs the popular [Flux.1-schnell](https://www.google.com/search?client=firefox-b-1-d&q=flux+schnell+) text-to-image model on Modal.
😓

2024-09-24 04:12 UTC, charlesfrye commented on 06_gpu_and_ml/stable_diffusion/flux.py
> +# # Flux.1 (Schnell)
```suggestion
# # Run Flux.1 (Schnell) on Modal
```

2024-09-24 04:12 UTC, charlesfrye commented on 06_gpu_and_ml/embeddings/instructor.py
> +# # Instructor Embedding
```suggestion
# # Create Instructor Embeddings on Modal
```

2024-09-24 04:13 UTC, charlesfrye commented on 06_gpu_and_ml/embeddings/text_embeddings_inference.py
> +# # Text Embeddings Inference
```suggestion
# # Run TextEmbeddingsInference (TEI) on Modal
```

2024-09-24 04:13 UTC, charlesfrye commented on 06_gpu_and_ml/stable_diffusion/playground.py
> +# # Playground v2.5
```suggestion
# # Run Playground v2.5 on Modal
```

2024-09-24 04:13 UTC, charlesfrye commented on 06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_lightning.py
> +# # SDXL Lightning
```suggestion
# # Run SDXL Lightning on Modal
```

2024-09-24 04:13 UTC, charlesfrye commented on 06_gpu_and_ml/stable_diffusion/stable_video_diffusion.py
> +# # Stable Video Diffusion
```suggestion
# # Run Stable Video Diffusion in a Streamlit app
```

2024-09-24 04:14 UTC, charlesfrye approved these changes

2024-09-24 04:29 UTC, merged