Add model weight storing on volumes to comfyui example further improvements section
modal-labs/modal-examples pull request #901
Opened 2024-10-01 13:31 UTC by kramstrom

### Type of Change

- [ ] New example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

## Checklist

- [ ] Example is testable in synthetic monitoring system, or `lambda-test: false` is added to example frontmatter (`---`)
  - [ ] Example is tested by executing with `modal run` or an alternative `cmd` is provided in the example frontmatter (e.g. `cmd: ["modal", "deploy"]`)
  - [ ] Example is tested by running with no arguments or the `args` are provided in the example frontmatter (e.g. `args: ["--prompt", "Formula for room temperature superconductor:"]`
- [ ] Example is documented with comments throughout, in a [_Literate Programming_](https://en.wikipedia.org/wiki/Literate_programming) style.
- [ ] Example does _not_ require third-party dependencies to be installed locally
- [ ] Example pins its dependencies
  - [ ] Example pins container images to a stable tag, not a dynamic tag like `latest`
  - [ ] Example specifies a `python_version` for the base image, if it is used
  - [ ] Example pins all dependencies to at least minor version, `~=x.y.z` or `==x.y`
  - [ ] Example dependencies with `version < 1` are pinned to patch version, `==0.y.z`

## Outside contributors

You're great! Thanks for your contribution.

2024-10-01 13:36 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-cc6c646.modal.run

2024-10-01 13:55 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-5b2f894.modal.run

2024-10-01 15:59 UTC, charlesfrye requested changes
Discussed offline -- we don't want to add this as a block of untested code at the end. Kasper is rewriting to merge this with the rest of the material.

2024-10-02 08:56 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-12cfa19.modal.run

2024-10-02 09:15 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-2e5b652.modal.run

2024-10-05 00:04 UTC, charlesfrye commented on 06_gpu_and_ml/comfyui/comfyapp.py
> +# Note that these dependencies are not installed locally
```suggestion
# Note that these dependencies are not installed locally.
```

2024-10-05 00:04 UTC, charlesfrye commented on 06_gpu_and_ml/comfyui/comfyapp.py
> +# they are only installed once in the remote environment where our app runs,
```suggestion
# They are only installed in the remote environment where our app runs.
```

2024-10-05 00:04 UTC, charlesfrye commented on 06_gpu_and_ml/comfyui/comfyapp.py
> +# on subsequent runs, the image will be cached and reused.
```suggestion
# This happens the first time. On subsequent runs, the cached image will be reused.
```

2024-10-05 00:05 UTC, charlesfrye commented on 06_gpu_and_ml/comfyui/comfyapp.py
> +# (alternatively, you can install them by cloning the git repositories to your `/root/comfy/ComfyUI/custom_nodes`
```suggestion
# Alternatively, you can install them by cloning the git repositories to your `/root/comfy/ComfyUI/custom_nodes`
```

2024-10-05 00:05 UTC, charlesfrye commented on 06_gpu_and_ml/comfyui/comfyapp.py
> +# directory and installing the required dependencies manually.)
```suggestion
# directory and installing the required dependencies manually.
```

2024-10-05 00:11 UTC, charlesfrye commented
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-8c3c5c7.modal.run

2024-10-05 00:12 UTC, charlesfrye approved these changes

2024-10-05 00:13 UTC, merged

2024-10-15 06:29 UTC, kramstrom commented
> it looks like here then that we're not publishing the volume-based approach and just telling people to append dependencies to the image definition to leverage caching?

Yeah we opted to go for the current approach with appending dependencies, if people really want to use volumes though we still have the gist to show how it could be done